'use client';

import Link from 'next/link';
import { motion } from 'framer-motion';
import { ArrowRight, CheckCircle2, Swords, Target } from 'lucide-react';
import CyberSamuraiBackground from '@/components/cyber-samurai-background';

const steps = [['01', 'Transmit intent', 'Type a real-world objective or summon a mission from the command core.'], ['02', 'Forge the path', 'Open the skill tree to convert a broad objective into focused, actionable moves.'], ['03', 'Claim the XP', 'Complete your directive, trigger the execution sequence, and build your legend.']];

export default function Home() {
  return <CyberSamuraiBackground><main className="mx-auto max-w-6xl px-5 pb-20 pt-6 sm:px-8">
    <nav className="flex items-center justify-between font-mono text-[10px] font-bold uppercase tracking-[.24em]"><span className="text-slate-800">Life <span className="text-pink-500">RPG</span> / shinobi network</span><Link href="/login" className="border border-pink-300 bg-white/80 px-3 py-2 text-pink-600 transition hover:bg-pink-500 hover:text-white">Enter deck</Link></nav>
    <section className="grid min-h-[72vh] items-center gap-12 py-20 lg:grid-cols-[1.25fr_.75fr]">
      <motion.div initial={{ opacity: 0, x: -28 }} animate={{ opacity: 1, x: 0 }} transition={{ duration: .7 }}><p className="mb-5 font-mono text-[11px] font-bold uppercase tracking-[.3em] text-pink-500">A field manual for deliberate growth</p><h1 className="max-w-3xl text-5xl font-black uppercase leading-[.9] tracking-tight text-slate-900 sm:text-7xl">Train like a <span className="text-pink-500">shinobi.</span><br />Live with intent.</h1><p className="mt-7 max-w-xl text-base leading-7 text-slate-600">Life RPG turns meaningful goals into a focused quest log. Set a directive, split it into skill moves, and make every completed action count.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/login" className="inline-flex items-center gap-2 rounded-sm bg-pink-500 px-5 py-3 font-mono text-xs font-bold uppercase tracking-wider text-white shadow-[0_8px_22px_rgba(236,72,153,.35)] transition hover:bg-pink-600">Begin your run <ArrowRight size={15}/></Link><a href="#manual" className="rounded-sm border border-slate-300 bg-white/70 px-5 py-3 font-mono text-xs font-bold uppercase tracking-wider text-slate-700 transition hover:border-pink-400">Read the manual</a></div></motion.div>
      <motion.div initial={{ opacity: 0, scale: .9 }} animate={{ opacity: 1, scale: 1 }} transition={{ delay: .15, duration: .7 }} className="mecha-panel relative border border-pink-200 bg-white/80 p-7 shadow-[0_22px_60px_rgba(190,24,93,.15)] backdrop-blur"><motion.div animate={{ y: [-8, 8, -8] }} transition={{ duration: 3.8, repeat: Infinity, ease: 'easeInOut' }} className="mx-auto grid h-40 w-40 place-items-center rounded-full border border-pink-300 bg-gradient-to-br from-white to-pink-100 shadow-[0_0_55px_rgba(236,72,153,.35)]"><Swords className="text-pink-500" size={65}/></motion.div><div className="mt-7 border-l-2 border-pink-400 pl-4 font-mono text-xs leading-6 text-slate-600"><span className="font-bold text-pink-600">UNIT S-01:</span> One intentional move at a time. Your legend is operational.</div></motion.div>
    </section>
    <section id="manual" className="scroll-mt-8 py-16"><motion.p initial={{ opacity: 0 }} whileInView={{ opacity: 1 }} viewport={{ once: true }} className="font-mono text-[11px] font-bold uppercase tracking-[.25em] text-pink-500">Operating manual</motion.p><div className="mt-6 grid gap-4 md:grid-cols-3">{steps.map(([number, title, body], i) => <motion.article key={number} initial={{ opacity: 0, y: 28 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: .2 }} transition={{ delay: i * .12 }} className="mecha-panel border border-slate-200 bg-white/80 p-6 shadow-sm"><span className="font-mono text-xs font-bold text-pink-500">{number}</span><h2 className="mt-5 text-xl font-black uppercase text-slate-900">{title}</h2><p className="mt-3 text-sm leading-6 text-slate-600">{body}</p></motion.article>)}</div></section>
    <motion.section initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} className="mecha-panel border border-pink-200 bg-pink-500 p-8 text-white shadow-[0_18px_48px_rgba(236,72,153,.28)]"><Target size={25}/><h2 className="mt-5 text-3xl font-black uppercase">No more vague goals.</h2><p className="mt-3 max-w-xl text-sm leading-6 text-pink-50">Deploy a directive, expose the next move, and collect the proof that you showed up.</p><Link href="/login" className="mt-6 inline-flex items-center gap-2 border border-white/70 bg-white px-4 py-3 font-mono text-xs font-bold uppercase tracking-wider text-pink-600"><CheckCircle2 size={15}/> Start the mission</Link></motion.section>
  </main></CyberSamuraiBackground>;
}
